// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/budbox-crm/BudboxCRM.tsx": () => import("../components/mockups/budbox-crm/BudboxCRM.tsx"),
  "./components/mockups/templates/BuildingBelongingWebinar-H4KCJc/Inclusion.tsx": () => import("../components/mockups/templates/BuildingBelongingWebinar-H4KCJc/Inclusion.tsx")
};
